code = []
code.append("from datetime import datetime")
code.append("")
code.append("class DailyReporter:")
code.append("    def __init__(self):")
code.append("        self.invoices = []")
code.append("")
code.append("    def record(self, invoice: dict):")
code.append("        self.invoices.append(invoice)")
code.append("")
code.append("    def generate_report(self) -> dict:")
code.append("        buyer_map = {}")
code.append("        for inv in self.invoices:")
code.append("            name = inv['buyer_name']")
code.append("            if name not in buyer_map:")
code.append("                buyer_map[name] = {")
code.append("                    'buyer_name': name,")
code.append("                    'invoice_count': 0,")
code.append("                    'total_value': 0.0,")
code.append("                    'fulfilled_items': 0,")
code.append("                    'missing_items': 0,")
code.append("                    'invoice_ids': [],")
code.append("                    'missing_skus': []")
code.append("                }")
code.append("            b = buyer_map[name]")
code.append("            b['invoice_count'] += 1")
code.append("            b['total_value'] += inv['totals']['subtotal']")
code.append(
    "            b['fulfilled_items'] += inv['totals']['fulfilled_item_count']")
code.append(
    "            b['missing_items'] += inv['totals']['unfulfilled_item_count']")
code.append("            b['invoice_ids'].append(inv['invoice_id'])")
code.append("            for u in inv['unfulfilled_items']:")
code.append("                b['missing_skus'].append({")
code.append("                    'sku': u['sku'],")
code.append("                    'shortage_pairs': u['shortage_pairs'],")
code.append("                    'status': u['status']")
code.append("                })")
code.append(
    "        total_revenue = sum(inv['totals']['subtotal'] for inv in self.invoices)")
code.append("        return {")
code.append("            'report_date': datetime.now().strftime('%Y-%m-%d'),")
code.append(
    "            'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M'),")
code.append("            'total_buyers': len(buyer_map),")
code.append("            'total_invoices': len(self.invoices),")
code.append("            'total_revenue': total_revenue,")
code.append("            'buyers': list(buyer_map.values())")
code.append("        }")
code.append("")
code.append("    def print_report(self):")
code.append("        report = self.generate_report()")
code.append("        print('\\n' + '='*55)")
code.append("        print('  VICTORY FOOTWEAR — DAILY REPORT')")
code.append("        print(f\"  Date       : {report['report_date']}\")")
code.append("        print(f\"  Generated  : {report['generated_at']}\")")
code.append("        print('='*55)")
code.append("        print(f\"  Total Buyers  : {report['total_buyers']}\")")
code.append("        print(f\"  Total Invoices: {report['total_invoices']}\")")
code.append(
    "        print(f\"  Total Revenue : {report['total_revenue']} tk\")")
code.append("        print('\\n  BUYER BREAKDOWN:')")
code.append("        for b in report['buyers']:")
code.append("            print(f\"  {b['buyer_name']}\")")
code.append("            print(f\"    Invoices : {b['invoice_count']}\")")
code.append("            print(f\"    Revenue  : {b['total_value']} tk\")")
code.append(
    "            print(f\"    Fulfilled: {b['fulfilled_items']} items\")")
code.append(
    "            print(f\"    Missing  : {b['missing_items']} items\")")
code.append("            if b['missing_skus']:")
code.append("                print(f\"    Missing SKUs:\")")
code.append("                for s in b['missing_skus']:")
code.append(
    "                    print(f\"      ❌ {s['sku']} — {s['shortage_pairs']} pairs [{s['status']}]\")")
code.append("        print('='*55)")

with open("reporter.py", "w", encoding="utf-8") as f:
    f.write("\n".join(code))

print("Done! reporter.py created successfully!")
