code = []
code.append("import json")
code.append("import os")
code.append("from order_parser import parse_order")
code.append("from inventory import InventoryManager, load_inventory_from_excel")
code.append("from invoice import generate_invoice, print_invoice")
code.append("from reporter import DailyReporter")
code.append("")
code.append(
    "EXCEL_PATH = r'E:\\PROJECT 01 (ORDER PROCESS)\\jj\\Stock Goods -06-05-2026.xlsx'")
code.append("")
code.append("def run_agent():")
code.append("    print('='*55)")
code.append("    print('  VICTORY FOOTWEAR — SALES ORDER AGENT')")
code.append("    print('='*55)")
code.append("    print('Loading inventory...')")
code.append("    inv = InventoryManager(load_inventory_from_excel(EXCEL_PATH))")
code.append("    print('Inventory loaded! 74 products ready.')")
code.append("    reporter = DailyReporter()")
code.append("    all_invoices = []")
code.append("    print('\\nPaste WhatsApp order messages below.')")
code.append(
    "    print('Type DONE when finished. Type REPORT for daily report.\\n')")
code.append("    while True:")
code.append("        print('-'*55)")
code.append("        lines = []")
code.append("        print('Enter order (press Enter twice when done):')")
code.append("        while True:")
code.append("            line = input()")
code.append("            if line.strip() == '':")
code.append("                break")
code.append("            if line.strip().upper() == 'DONE':")
code.append("                print('\\nSession ended.')")
code.append("                reporter.print_report()")
code.append("                report = reporter.generate_report()")
code.append(
    "                with open('daily_report.json','w',encoding='utf-8') as f:")
code.append(
    "                    json.dump(report, f, indent=2, ensure_ascii=False)")
code.append("                print('\\nDaily report saved to daily_report.json')")
code.append("                return")
code.append("            if line.strip().upper() == 'REPORT':")
code.append("                reporter.print_report()")
code.append("                break")
code.append("            lines.append(line)")
code.append("        if not lines:")
code.append("            continue")
code.append("        message = '\\n'.join(lines)")
code.append("        print('\\nParsing order with AI...')")
code.append("        parsed = parse_order(message)")
code.append("        print(f\"Buyer: {parsed.get('buyer_name','Unknown')}\")")
code.append("        print(f\"Items found: {len(parsed.get('items',[]))}\")")
code.append("        print('Generating invoice...')")
code.append("        invoice = generate_invoice(parsed, inv)")
code.append("        print_invoice(invoice)")
code.append("        reporter.record(invoice)")
code.append("        all_invoices.append(invoice)")
code.append(
    "        with open(f\"invoice_{invoice['invoice_id']}.json\",'w',encoding='utf-8') as f:")
code.append("            json.dump(invoice, f, indent=2, ensure_ascii=False)")
code.append(
    "        print(f\"Invoice saved to invoice_{invoice['invoice_id']}.json\")")
code.append("")
code.append("if __name__ == '__main__':")
code.append("    run_agent()")

with open("main.py", "w", encoding="utf-8") as f:
    f.write("\n".join(code))

print("Done! main.py created successfully!")
